# Generated by Django 5.1.3 on 2025-01-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='task',
            field=models.CharField(default='task 1', max_length=50),
            preserve_default=False,
        ),
    ]
